config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "home#index"

  devise_for :admins, :path => '/admins'
  get 'admins/dashboard', to: 'admins#index'

  get 'registrations/update'
  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'dashboard', to: 'users#index'

  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  resources :users

  resources :articles do
    resources :comments
  end

end

app/views/admins/index.html.erb
<div class="d-flex w-100 justify-content-around">
  <h1>Dashboard page</h1>
  <%= link_to 'New user', new_user_path %>
  <% if admin_signed_in? %>
    <button><%= 
      link_to 'Logout', signout_path,
      method: :delete, 
      data: { confirm: 'Do you want to log out?' } 
    %></button>
  <% end %>
</div>
<div>
<p>it is <%= @time %></p>
<div class="w-75 m-auto">
  <table class="table text-center">
  <thead>
    <tr>
      <th scope="col">User ID</th>
      <th scope="col">Email</th>
      <th scope="col">Username</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td class="d-flex justify-content-center">
          <%= link_to "update", edit_user_path(user), class: 'px-3 d-block' %>
          <%= link_to "destroy", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></p>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>